### ISSUE TITLE
API Key notes vague/confusing

### ISSUE THREAD

**Issue by adamantinus26** [supabase/stripe-sync-engine#117]
The Readme.md documentation does not denote what the API Key (found in the first paragraph of the .env file) is for the stripe sync engine.

At first glance, it could be either the publishable stripe key, or one of the two keys generated from the JWT Secret

It could not be the secret stripe api key, since that is included further down as an optional component. It also could not be the database password.

I don't know which it is supposed to be -- my assumption/first guess is for the publishable stripe key since that is also used for reciepts/payment acknowledgement at customer-facing payment portals.

**Comment by oscarhermoso** [comment]
I agree documentation could be improved.

You should generate a new random value to use for your API key (eg. with `openssl rand -hex 16`). Do not use a publishable key.

This must be set as the `Authorization` header in any "non-Stripe" requests to be processed by the container.

For example, if you want the container to [backfill customers from Stripe](https://github.com/supabase/stripe-sync-engine?tab=readme-ov-file#backfill-from-stripe), then the `Authorization` header must match.

https://github.com/supabase/stripe-sync-engine/blob/c67ae3ecd0e341b4dad5c57fe281556bf14154c7/src/routes/sync.ts#L7-L10

https://github.com/supabase/stripe-sync-engine/blob/c67ae3ecd0e341b4dad5c57fe281556bf14154c7/src/utils/verifyApiKey.ts#L6-L17

**Comment by kevcodez** [comment]
As @oscarhermoso has pointed out, this is for the "admin" endpoints. If your service is not exposed to the internet, you can set it to basically anything - if your service is publicly accessible, you should set it to anything secure (i.e. 32 char random string).
