### ISSUE TITLE
Make subscriptions.plan a jsonb column

### ISSUE THREAD

**Issue by inian** [supabase/stripe-sync-engine#14]
Is there a reason behind [it being a text column](https://github.com/supabase/stripe-sync-engine/blob/2a8c1746ffe2aa0ce7f47651de76335b96b787d5/db/migrations/20210429140401_subscriptions.sql#L40) now? 

It will be cool if we can make it a jsonb column.

**Comment by kiwicopple** [comment]
This should actually be a reference to the `plans` table

https://github.com/supabase/stripe-sync-engine/blob/2a8c1746ff/db/migrations/20210501054146_plans.sql

But we haven't finished that functionality. Do we need it asap @inian ? I can implement it today

**Comment by inian** [comment]
Not urgent at all, I later found that you have a view called `project_subscriptions` which has a jsonb column called `plans` which works for me!

**Comment by phamhieu** [comment]
[Stripe replaced Plans api by Prices api](https://stripe.com/docs/billing/migration/migrating-prices). Won't fix.
