### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by CalebDelbridge** [supabase/stripe-sync-engine#16]
It seems that there was a pull request merged to create an image to support arm64, but no new release has been created

**Comment by kiwicopple** [comment]
fix commit running here:
https://github.com/supabase/stripe-sync-engine/actions/runs/1122386737

**Comment by kiwicopple** [comment]
Hey @soedirgo it looks like this fix didn't come through on the release
https://github.com/supabase/stripe-sync-engine/pull/10/files


Any ideas?

**Comment by darora** [comment]
`chore(release)` is not expected to trigger a release under the default rules; c.f. https://github.com/semantic-release/commit-analyzer#default-rules-matching

**Comment by soedirgo** [comment]
Should be fixed with https://github.com/supabase/stripe-sync-engine/commit/c18bbe36e3b305f0ebbb85e090a0b32d3e247a81. @CalebDelbridge let us know if the aarch64 image doesn't work for you

**Comment by Indirectelex** [comment]
Hey folks, we're trying to install Supabase on Raspberry pi 4, so on ARM64. Please could you give us an url to copy paste the docker-compose file?

**Comment by soedirgo** [comment]
@Indirectelex not all the Docker images support arm64 right now, this is tracked on https://github.com/supabase/supabase/issues/2954.

**Comment by Indirectelex** [comment]
thanks

Le mar. 22 mars 2022 à 04:13, Bobbie Soedirgo ***@***.***> a
écrit :

**Comment by soedirgo** [comment]
Sorry, let me correct that - we have arm64 images for the Compose setup, but apparently there are some issues with the supabase/postgres image on arm64, tracked in https://github.com/supabase/supabase/issues/4887
