### ISSUE TITLE
Test webhooks cannot call "customer.created"

### ISSUE THREAD

**Issue by gokaykucuk** [supabase/stripe-sync-engine#29]
# Bug report

## Describe the bug

After setting up a stripe account, if the webhooks are added in "test mode", webhooks seems like missing the field `next_invoice_sequence` which creates the following error;
```
Missing value for statement.\nnext_invoice_sequence not provided for statement
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a webhook in test mode
2. Enable it and trigger a test webhook or go through a payment in "test mode".
3. See error

## Expected behavior

No 500's are returned and data is inserted to PostgreSQL.

**Comment by gokaykucuk** [comment]
`customer.updated` also has the same issue,  while `invoice` webhooks fail with`next_invoice_sequence`

**Comment by kiwicopple** [comment]
Hmm I wonder if I broke something with my latest release
https://github.com/supabase/stripe-sync-engine/compare/v0.1.4...v0.2.0

**Comment by gokaykucuk** [comment]
@kiwicopple doesn't seem those changes are related to this issue. Was it working under "test mode"? I was thinking maybe this parameter is missing from "test mode"?

**Comment by mikewongblinx** [comment]
Hey. I wonder is this problem get handled? Seem it found a year before

**Comment by kiwicopple** [comment]
I'll close this for now. If anyone else encounters this error, please let us know

**Comment by epavanello** [comment]
I found the same error with both the test and production versions of Stripe

**Comment by psteinroe** [comment]
same issue here
