### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [supabase/stripe-sync-engine#73]
Hi folks!

I stumbled on this repo and saw a lot of similarities to our [Stripe Source Plugin](https://www.cloudquery.io/docs/plugins/sources/stripe/overview).

I thought it might be potentially interesting to collaborate here. Potentially we can start with some mutual guides (as it should work as is with no additional code) on how to use CloudQuery source plugins and sync those to a Postgres supabase database. If we see tracation we can potentially think on a tighter integration.

I think this might be a win-win for both sides as this should save a lot of time developing an ELT plugin on your end and get a lot of features out of the box (like concurrency, rich type system with more than 14 types, destination agnostic, incremental syncing and others), and on our end we can get more people contributing and helping us maintain plugins like Stripe.

Let me know what you think? Im also available at `yp` at `cloudquery.io` or our discord at https://cloudquery.io/discord for offline discussion.

Thanks!
Yevgeny

**Comment by kiwicopple** [comment]
Thanks for the interest @yevgenypats . This isn't really a strategic product for Supabase, it's just one that we use internally ( you won't see it in our docs, for example)

I'll let the API team know about your Plugin and see if they want to migrate to that instead! Also feel free to check out our integrations page if you want to develop a supabase/postgres integration for CloudQuery: https://supabase.com/partners/integrations

**Comment by yevgenypats** [comment]
Thanks for the quick response @kiwicopple ! That makes sense. I took a loot at the integration page, didn't find a quick use-case or similar thing on top of my head at this moment but yeah if the API team might want to give CQ a try, instead of maintaining this, I'd love to help with that.
